[bootimg]
base = 0x0
kernel = 0x8000
ramdisk = 0x1000000
second = 0
tags = 0x100
pagesize = 4096

[[device]]
vendor = "google"
model = "blueline"

[[device]]
vendor = "lg"
model = "judyln"

[[device]]
vendor = "lg"
model = "judyp"

[[device]]
vendor = "oneplus"
model = "enchilada"
append = "console=ttyMSM0,115200"

[[device]]
vendor = "oneplus"
model = "fajita"
append = "console=ttyMSM0,115200"

[[device]]
vendor = "samsung"
model = "starqltechn"

[[device]]
vendor = "shift"
model = "axolotl"
append = "console=ttyMSM0,115200"

[[device]]
vendor = "sony"
model = "xperia-tama-akari"

[[device]]
vendor = "sony"
model = "xperia-tama-akatsuki"

[[device]]
vendor = "sony"
model = "xperia-tama-apollo"

[[device]]
vendor = "xiaomi"
model = "beryllium"
variant = "ebbg"

[[device]]
vendor = "xiaomi"
model = "beryllium"
variant = "tianma"

[[device]]
vendor = "xiaomi"
model = "polaris"
